version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mydata:/db
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: employees

  postgres:
    image: postgres 
    restart: always
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees

  mysqladminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgresadminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080